In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.3.1+cu121
False


Practice with tensors

In [ ]:
## practice tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# vector tensor is 1 dimentional, shape is in 2
vect = torch.tensor( [7, 7] )
vect.ndim

1

In [ ]:
matrix = torch.tensor([[7, 8],[9, 10]])
matrix[0]

tensor([7, 8])

In [ ]:
# dimensions of tensor
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

Often the starting point for neural networks

In [ ]:
# create random tensor with dimensions (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5980, 0.8403, 0.2904, 0.3985],
        [0.6203, 0.7767, 0.0470, 0.2068],
        [0.5842, 0.3096, 0.6113, 0.0226]])

In [ ]:
# tensor of all 0s, useful for masking
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Creating a range of tensors or tensors-like


In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
tensor_like = torch.zeros_like(input=one_to_ten)
tensor_like

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes

In [ ]:
# default is float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

# Manipulating tensors

In [ ]:
# scalar operations
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
# element wise multiplication
print(tensor, "*", tensor, "is ")
tensor * tensor

tensor([1, 2, 3]) * tensor([1, 2, 3]) is 


tensor([1, 4, 9])

In [ ]:
# matrix multiplication
# remember inner dimensions must match, result has shape of outer dimensions
matrixOne = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrixTwo = torch.tensor([[1, 2], [3, 4], [5, 6]])
torch.matmul(matrixOne, matrixTwo)
# can also use @ symbol, does same thing

tensor([[22, 28],
        [49, 64]])

In [ ]:
# transpose matrices
print("Original\n", matrixOne, "\nTransposed:\n", matrixOne.T)

Original
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
Transposed:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


# Tensor Aggregation

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
# find positional min and max
# where max appears
x.argmax()

tensor(9)

# Reshaping, stacking, squeezing, unsqueezing tensors

Stacking - combining multiple tensors on top of each other, vstack, or side by side, hstack

squeeze - removes all '1' dimensions from a tensor

unsqueeze - add a '1' dimension to target tensor

Permute - return a view of input with dimentions permuted

In [ ]:
# reshaping, stacking, squeezing, unsqueezing tensors
y = torch.arange(start=1., end=11., step=1)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
y_reshaped = y.reshape(2, 5)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# change the view
# view similar to reshape, but it shares the same memory
z = y.view(1, 10)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
z[:, 0] = 5
z, y

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# stack tensors on top of each other
# dim = 1 is v-stack
x_stacked = torch.stack( [x, x, x, x], dim = 1)
x_stacked

tensor([[ 0,  0,  0,  0],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [ ]:
# unsqueeze adds a dimention to tensor at specific dimension
print(x, x.shape)
x = x.unsqueeze(dim=0)
print(x, x.shape)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]) torch.Size([1, 10])
tensor([[[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]]) torch.Size([1, 1, 10])


In [ ]:
# permte rearanges dimensions of target tensor in specified order
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)

# permute returns a new view
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

Indexing is similar with Numpy

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# : to select all of a single dimension
x, x[:, :, 1]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[2, 5, 8]]))

# PyTorch tensors and NumPy

In [ ]:
import torch
import numpy as np

# pytorch will reflect datatyp of numpy array
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducibility

Randomness needs random seed

In [ ]:
import torch

rand_a = torch.rand(3,4)
rand_b = torch.rand(3,4)

print(rand_a, "\n", rand_b)
print(rand_a == rand_b)

tensor([[0.3992, 0.4229, 0.8683, 0.0403],
        [0.6250, 0.0520, 0.8386, 0.7103],
        [0.3364, 0.1205, 0.4394, 0.7703]]) 
 tensor([[0.7931, 0.3034, 0.8615, 0.5489],
        [0.4877, 0.3087, 0.7068, 0.6015],
        [0.4397, 0.6162, 0.9023, 0.1337]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random but reproducable
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_d = torch.rand(3,4)

print(rand_c, "\n", rand_d)
print(rand_c == rand_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Tensors on GPU

In [ ]:
import torch
# tensors, default on CPU
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
# moving tensors back to CPU
# (numpy only for CPU)
tensor_back_on_gpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_gpu

array([1, 2, 3])